### ISSUE TITLE
jpmml-r .jar file issue

### ISSUE THREAD

**Issue by ghost321** [jpmml/jpmml-r#1]
Hi,

I'm trying to convert my gbm model to pmml by changing it into RDS format first and then use command line java to change it into pmml. This is the code i'm using..

saveRDS(model, "model.rds") ## Using R to build a model

java -jar target/converter-executable-1.1-SNAPSHOT.jar --rds-input model.rds --pmml-output model.pmml  ## Using java to to convert to pmml in terminal(mac)

However this is the error i get - "Error: Unable to access jarfile target/converter-executable-1.1-SNAPSHOT.jar"

I'm using Java version "1.8.0_65" 64-bit. Any help appreciated.

**Comment by vruusmann** [comment]
This JAR file does not exist in source checkout. It comes into existence when you build the source checkout locally using Apache Maven: `mvn clean install`.

If the JAR file exists, but Java cannot access it, then perhaps there's a problem with file permissions? Have you tried chmodding it to `777`?

JPMML-R is a rather developer-oriented project. If you're looking for user-oriented R-to-PMML conversion functionality, then you should consider using the [`r2pmml`] (https://github.com/jpmml/r2pmml) package instead.

**Comment by ghost321** [comment]
Hi Villu,

I tried using r2pmml also, but I get a java lang error...This is the link to my question on stackoverflow [](http://stackoverflow.com/questions/33882019/problems-with-r2pmml)

Could you please let me know what i'm doing wrong. Thanks!

**Comment by vruusmann** [comment]
I can't find the description of your "java lang error" anywhere.

According to SO, there seems to be an issue with using the `r2pmml` package on Mac (the culprit is the `rJava` package, which includes its own (outdated?) Java executable, which "shadows" the system-level Java executable?).

I have just redesigned/updated the `r2pmml` package so that it no longer has the `rJava` package dependency. Could you re-install the `r2pmml` package and see if your "java lang error" has been righted? As a bonus, the updated `r2pmml` package has now full support for multi-class classification `gbm` and `xgb.Booster` model objects.

**Comment by vruusmann** [comment]
Closing as invalid, because there's not enough information/feedback from the user to take extra action.
